import {
  NDISSupportItem,
  UserProfile,
  Client,
  Practitioner,
  RestrictivePractice,
  Incident,
  CaseNote,
  Lead,
  ABCLog,
  BillingClaim,
  BSPDocument,
  AppNotification,
  CRMTask,
  AuditLog
} from '@/types';

export const OFFICIAL_2026_NDIS_PRICE_GUIDE: NDISSupportItem[] = [
  {
    code: '07_002_0115_8_3',
    name: 'Specialist Behavioural Intervention Support',
    category: 'Capacity Building - Relationships',
    pricePerUnit: 214.41,
    unitOfMeasure: 'Hour',
  },
  {
    code: '07_004_0115_8_3',
    name: 'Individual Behaviour Support Plan Development & Training',
    category: 'Capacity Building - Relationships',
    pricePerUnit: 214.41,
    unitOfMeasure: 'Hour',
  },
  {
    code: '15_056_0128_1_3',
    name: 'Assessment Recommendation Therapy Support - Allied Health',
    category: 'Capacity Building - Improved Daily Living',
    pricePerUnit: 193.99,
    unitOfMeasure: 'Hour',
  },
  {
    code: '15_043_0128_1_3',
    name: 'Dietitian Consultation & Meal Planning Supports',
    category: 'Capacity Building - Improved Daily Living',
    pricePerUnit: 193.99,
    unitOfMeasure: 'Hour',
  },
  {
    code: '15_054_0128_1_3',
    name: 'Speech Pathology Assessment & Augmentative Communication',
    category: 'Capacity Building - Improved Daily Living',
    pricePerUnit: 193.99,
    unitOfMeasure: 'Hour',
  },
  {
    code: '15_055_0128_1_3',
    name: 'Occupational Therapy Sensory Profiling & Environmental Audit',
    category: 'Capacity Building - Improved Daily Living',
    pricePerUnit: 193.99,
    unitOfMeasure: 'Hour',
  },
  {
    code: '07_001_0106_8_3',
    name: 'Support Coordination - Level 2: Coordination of Supports',
    category: 'Capacity Building - Support Coordination',
    pricePerUnit: 100.14,
    unitOfMeasure: 'Hour',
  },
  {
    code: '07_002_0132_8_3',
    name: 'Specialist Support Coordination - Level 3: High Complex Needs',
    category: 'Capacity Building - Support Coordination',
    pricePerUnit: 190.54,
    unitOfMeasure: 'Hour',
  },
  {
    code: '01_011_0107_1_1',
    name: 'Assistance With Self-Care Activities - Standard Weekday Daytime',
    category: 'Core - Assistance with Daily Life',
    pricePerUnit: 67.56,
    unitOfMeasure: 'Hour',
  },
  {
    code: '01_015_0107_1_1',
    name: 'Assistance With Self-Care Activities - Weekday Evening',
    category: 'Core - Assistance with Daily Life',
    pricePerUnit: 74.44,
    unitOfMeasure: 'Hour',
  },
  {
    code: '01_013_0107_1_1',
    name: 'Assistance With Self-Care Activities - Saturday Support',
    category: 'Core - Assistance with Daily Life',
    pricePerUnit: 95.07,
    unitOfMeasure: 'Hour',
  },
  {
    code: '01_014_0107_1_1',
    name: 'Assistance With Self-Care Activities - Sunday Support',
    category: 'Core - Assistance with Daily Life',
    pricePerUnit: 122.59,
    unitOfMeasure: 'Hour',
  },
  {
    code: '04_104_0125_6_1',
    name: 'Access Community, Social and Rec Activities - Standard Weekday',
    category: 'Core - Social & Community Participation',
    pricePerUnit: 67.56,
    unitOfMeasure: 'Hour',
  },
  {
    code: '05_220600111_0105_1_2',
    name: 'Low Cost Assistive Technology for Sensory & Communication Support',
    category: 'Capital - Assistive Technology',
    pricePerUnit: 495.00,
    unitOfMeasure: 'Each',
  },
];

export const INITIAL_USERS: UserProfile[] = [
  {
    id: 'user-director',
    name: 'Dr. Sarah Jenkins',
    email: 'sarah.jenkins@breakthrough.org.au',
    role: 'ADMIN',
    position: 'Clinical Director & Principal PBS Specialist',
    practitionerId: 'prac-201',
    workerScreeningStatus: 'Active',
    workerScreeningExpiry: '2028-09-30',
    policeCheckExpiry: '2027-11-15',
    ndisOrientationDone: true,
    activeCaseload: 14,
  },
  {
    id: 'user-specialist',
    name: 'Marcus Vance',
    email: 'marcus.vance@breakthrough.org.au',
    role: 'PRACTITIONER',
    position: 'Senior Behaviour Support Practitioner',
    practitionerId: 'prac-202',
    workerScreeningStatus: 'Active',
    workerScreeningExpiry: '2027-05-12',
    policeCheckExpiry: '2026-10-20',
    ndisOrientationDone: true,
    activeCaseload: 18,
  },
  {
    id: 'user-auditor',
    name: 'Elena Rostova',
    email: 'elena.rostova@breakthrough.org.au',
    role: 'VIEWER',
    position: 'Compliance & Quality Safeguards Officer',
    practitionerId: 'prac-203',
    workerScreeningStatus: 'Active',
    workerScreeningExpiry: '2028-01-14',
    policeCheckExpiry: '2027-06-30',
    ndisOrientationDone: true,
    activeCaseload: 0,
  },
  {
    id: 'user-coordinator',
    name: 'Sarah Davies',
    email: 'sarah.davies@breakthrough.org.au',
    role: 'SUPPORT_COORDINATOR',
    position: 'Lead Support Coordinator & Intake Specialist',
    practitionerId: 'prac-204',
    workerScreeningStatus: 'Active',
    workerScreeningExpiry: '2027-11-20',
    policeCheckExpiry: '2026-12-15',
    ndisOrientationDone: true,
    activeCaseload: 22,
  },
];

export const STANDARD_DRIVE_SUBFOLDERS = [
  'Goals Statement',
  'Emergency and Disaster Plan',
  'BSP',
  'Invoices',
  'FBA',
  'NDIS Plan',
  'Letters/ Correspondence',
  'Consent Form',
  'Assessments/ Reports',
  'Referral Form',
  'Progress Notes',
  'Service Agreement'
];

export const COMPANY_DRIVE_PARTICIPANTS: Client[] = [
  {
    id: 'cli-ben-rusic',
    ndisNumber: '430918234',
    name: 'Ben Rusic',
    dateOfBirth: '2006-04-12',
    status: 'Active',
    primaryDisability: 'Autism Spectrum Disorder (Level 3)',
    secondaryDisabilities: ['Sensory Processing Sensitivity', 'Severe Communication Impairment'],
    isCompanyDriveParticipant: true,
    driveFolderPath: 'Staff Share Drive > Participants > Behaviour Support > Ben Rusic',
    driveFolderUrl: 'https://drive.google.com/drive/u/1/folders/1dLRioOoPCTOUNZW-BenRusic',
    driveSubfolders: STANDARD_DRIVE_SUBFOLDERS,
    goals: [
      {
        id: 'g-ben-1',
        title: 'Master independent emotional regulation strategies during community outings to reduce sensory overload',
        category: 'Capacity Building',
        targetDate: '2026-12-31',
        progressPercent: 72,
        status: 'In Progress',
        gasScore: 1
      },
      {
        id: 'g-ben-2',
        title: 'Increase autonomous functional communication using AAC tablet across daily living routines',
        category: 'Core',
        targetDate: '2026-11-15',
        progressPercent: 85,
        status: 'In Progress',
        gasScore: 1
      }
    ],
    planStartDate: '2026-01-01',
    planEndDate: '2026-12-31',
    totalBudget: 62000,
    allocatedBudget: 55000,
    spentBudget: 28400,
    primaryPractitionerId: 'prac-202',
    primaryPractitionerName: 'Marcus Vance',
    riskLevel: 'High',
    emergencyContact: {
      name: 'Maria Rusic',
      relationship: 'Mother & Primary Nominee',
      phone: '0412 901 882'
    },
    restrictivePracticesActive: true,
    createdAt: '2026-01-10T08:00:00Z',
    updatedAt: '2026-09-20T10:30:00Z'
  },
  {
    id: 'cli-jenelle-rusic',
    ndisNumber: '430918235',
    name: 'Jenelle Rusic',
    dateOfBirth: '2008-08-25',
    status: 'Active',
    primaryDisability: 'Autism Spectrum Disorder (Level 2)',
    secondaryDisabilities: ['Generalized Anxiety Disorder'],
    isCompanyDriveParticipant: true,
    driveFolderPath: 'Staff Share Drive > Participants > Behaviour Support > Jenelle Rusic',
    driveFolderUrl: 'https://drive.google.com/drive/u/1/folders/1jd5KeDWRr2-JenelleRusic',
    driveSubfolders: STANDARD_DRIVE_SUBFOLDERS,
    goals: [
      {
        id: 'g-jen-1',
        title: 'Develop positive coping mechanisms for classroom and social environment transitions',
        category: 'Capacity Building',
        targetDate: '2026-12-15',
        progressPercent: 65,
        status: 'In Progress',
        gasScore: 0
      }
    ],
    planStartDate: '2026-02-01',
    planEndDate: '2027-01-31',
    totalBudget: 42000,
    allocatedBudget: 38000,
    spentBudget: 16500,
    primaryPractitionerId: 'prac-201',
    primaryPractitionerName: 'Dr. Sarah Jenkins',
    riskLevel: 'Medium',
    emergencyContact: {
      name: 'Maria Rusic',
      relationship: 'Mother',
      phone: '0412 901 882'
    },
    restrictivePracticesActive: false,
    createdAt: '2026-02-01T08:00:00Z',
    updatedAt: '2026-09-18T14:20:00Z'
  },
  {
    id: 'cli-eman-syed',
    ndisNumber: '431872619',
    name: 'Eman Syed',
    dateOfBirth: '2005-01-18',
    status: 'Active',
    primaryDisability: 'Intellectual Disability (Moderate)',
    secondaryDisabilities: ['Expressive Language Disorder', 'Sensory Avoidance'],
    isCompanyDriveParticipant: true,
    driveFolderPath: 'Staff Share Drive > Participants > Behaviour Support > Eman Syed',
    driveFolderUrl: 'https://drive.google.com/drive/u/1/folders/1jd5KeDWRr2-EmanSyed',
    driveSubfolders: STANDARD_DRIVE_SUBFOLDERS,
    goals: [
      {
        id: 'g-eman-1',
        title: 'Implement proactive behaviour support strategies to decrease self-injurious behaviour during fatigue',
        category: 'Capacity Building',
        targetDate: '2026-11-30',
        progressPercent: 60,
        status: 'In Progress',
        gasScore: 0
      }
    ],
    planStartDate: '2026-01-15',
    planEndDate: '2027-01-14',
    totalBudget: 58000,
    allocatedBudget: 52000,
    spentBudget: 27100,
    primaryPractitionerId: 'prac-202',
    primaryPractitionerName: 'Marcus Vance',
    riskLevel: 'High',
    emergencyContact: {
      name: 'Farhan Syed',
      relationship: 'Father',
      phone: '0423 456 781'
    },
    restrictivePracticesActive: true,
    createdAt: '2026-01-15T09:00:00Z',
    updatedAt: '2026-09-15T11:45:00Z'
  },
  {
    id: 'cli-reyansh-chawla',
    ndisNumber: '432109845',
    name: 'Reyansh Chawla',
    dateOfBirth: '2011-09-03',
    status: 'Active',
    primaryDisability: 'Autism Spectrum Disorder (Level 3)',
    secondaryDisabilities: ['Non-verbal / AAC User', 'Severe Sensory Modulation Differences'],
    isCompanyDriveParticipant: true,
    driveFolderPath: 'Staff Share Drive > Participants > Behaviour Support > Reyansh Chawla',
    driveFolderUrl: 'https://drive.google.com/drive/u/1/folders/1jd5KeDWRr2-ReyanshChawla',
    driveSubfolders: STANDARD_DRIVE_SUBFOLDERS,
    goals: [
      {
        id: 'g-rey-1',
        title: 'Establish visual schedules and proactive replacement behaviours for mealtime transitions',
        category: 'Capacity Building',
        targetDate: '2026-12-31',
        progressPercent: 78,
        status: 'In Progress',
        gasScore: 1
      }
    ],
    planStartDate: '2025-11-01',
    planEndDate: '2026-10-31',
    totalBudget: 66000,
    allocatedBudget: 60000,
    spentBudget: 48900,
    primaryPractitionerId: 'prac-201',
    primaryPractitionerName: 'Dr. Sarah Jenkins',
    riskLevel: 'High',
    emergencyContact: {
      name: 'Pooja Chawla',
      relationship: 'Mother',
      phone: '0431 889 002'
    },
    restrictivePracticesActive: true,
    createdAt: '2025-11-01T08:30:00Z',
    updatedAt: '2026-09-22T09:15:00Z'
  },
  {
    id: 'cli-ayaan-ayaan',
    ndisNumber: '433981240',
    name: 'Ayaan Ayaan',
    dateOfBirth: '2007-06-14',
    status: 'Active',
    primaryDisability: 'Global Developmental Delay',
    secondaryDisabilities: ['Sensory Seeking Behaviours', 'Hyperactivity'],
    isCompanyDriveParticipant: true,
    driveFolderPath: 'Staff Share Drive > Participants > Behaviour Support > Ayaan Ayaan',
    driveFolderUrl: 'https://drive.google.com/drive/u/1/folders/1jd5KeDWRr2-AyaanAyaan',
    driveSubfolders: STANDARD_DRIVE_SUBFOLDERS,
    goals: [
      {
        id: 'g-ay-1',
        title: 'Maintain community engagement via structured physical activity and sensory diet routines',
        category: 'Social & Community',
        targetDate: '2026-10-31',
        progressPercent: 70,
        status: 'In Progress',
        gasScore: 1
      }
    ],
    planStartDate: '2026-03-01',
    planEndDate: '2027-02-28',
    totalBudget: 45000,
    allocatedBudget: 40000,
    spentBudget: 18200,
    primaryPractitionerId: 'prac-202',
    primaryPractitionerName: 'Marcus Vance',
    riskLevel: 'Medium',
    emergencyContact: {
      name: 'Zahra Ayaan',
      relationship: 'Mother',
      phone: '0408 332 119'
    },
    restrictivePracticesActive: false,
    createdAt: '2026-03-01T09:00:00Z',
    updatedAt: '2026-09-12T16:00:00Z'
  },
  {
    id: 'cli-ryan-syed',
    ndisNumber: '431872620',
    name: 'Ryan Syed',
    dateOfBirth: '2009-11-30',
    status: 'Active',
    primaryDisability: 'Autism Spectrum Disorder (Level 2)',
    secondaryDisabilities: ['Emotional Dysregulation', 'Impulse Management Challenges'],
    isCompanyDriveParticipant: true,
    driveFolderPath: 'Staff Share Drive > Participants > Behaviour Support > Ryan Syed',
    driveFolderUrl: 'https://drive.google.com/drive/u/1/folders/1jd5KeDWRr2-RyanSyed',
    driveSubfolders: STANDARD_DRIVE_SUBFOLDERS,
    goals: [
      {
        id: 'g-ry-1',
        title: 'Learn calm-down strategies and emotion vocabulary to communicate distress safely',
        category: 'Capacity Building',
        targetDate: '2026-12-15',
        progressPercent: 58,
        status: 'In Progress',
        gasScore: 0
      }
    ],
    planStartDate: '2026-02-15',
    planEndDate: '2027-02-14',
    totalBudget: 49000,
    allocatedBudget: 44000,
    spentBudget: 19800,
    primaryPractitionerId: 'prac-201',
    primaryPractitionerName: 'Dr. Sarah Jenkins',
    riskLevel: 'Medium',
    emergencyContact: {
      name: 'Farhan Syed',
      relationship: 'Father',
      phone: '0423 456 781'
    },
    restrictivePracticesActive: false,
    createdAt: '2026-02-15T08:00:00Z',
    updatedAt: '2026-09-14T13:10:00Z'
  },
  {
    id: 'cli-ryder-warburton',
    ndisNumber: '434551982',
    name: 'Ryder Warburton',
    dateOfBirth: '2012-03-21',
    status: 'Active',
    primaryDisability: 'ADHD (Combined Type)',
    secondaryDisabilities: ['Oppositional Defiant Behaviours', 'Sensory Seeking'],
    isCompanyDriveParticipant: true,
    driveFolderPath: 'Staff Share Drive > Participants > Behaviour Support > Ryder Warburton',
    driveFolderUrl: 'https://drive.google.com/drive/u/1/folders/1jd5KeDWRr2-RyderWarburton',
    driveSubfolders: STANDARD_DRIVE_SUBFOLDERS,
    goals: [
      {
        id: 'g-war-1',
        title: 'Increase sustained task focus and tolerance for non-preferred activities in home setting',
        category: 'Capacity Building',
        targetDate: '2026-11-20',
        progressPercent: 62,
        status: 'In Progress',
        gasScore: 0
      }
    ],
    planStartDate: '2026-01-20',
    planEndDate: '2027-01-19',
    totalBudget: 39000,
    allocatedBudget: 35000,
    spentBudget: 15400,
    primaryPractitionerId: 'prac-202',
    primaryPractitionerName: 'Marcus Vance',
    riskLevel: 'Medium',
    emergencyContact: {
      name: 'Liam Warburton',
      relationship: 'Father',
      phone: '0419 778 201'
    },
    restrictivePracticesActive: false,
    createdAt: '2026-01-20T10:00:00Z',
    updatedAt: '2026-09-19T15:30:00Z'
  },
  {
    id: 'cli-indiana-mckenzie',
    ndisNumber: '435672891',
    name: 'Indiana McKenzie',
    dateOfBirth: '2004-12-05',
    status: 'Active',
    primaryDisability: 'Psychosocial Disability / Complex PTSD',
    secondaryDisabilities: ['Severe Social Anxiety', 'Panic Reactions'],
    isCompanyDriveParticipant: true,
    driveFolderPath: 'Staff Share Drive > Participants > Behaviour Support > Indiana McKenzie',
    driveFolderUrl: 'https://drive.google.com/drive/u/1/folders/1jd5KeDWRr2-IndianaMcKenzie',
    driveSubfolders: STANDARD_DRIVE_SUBFOLDERS,
    goals: [
      {
        id: 'g-mck-1',
        title: 'Establish trauma-informed de-escalation protocols and safe spaces for panic management',
        category: 'Capacity Building',
        targetDate: '2026-12-31',
        progressPercent: 75,
        status: 'In Progress',
        gasScore: 1
      }
    ],
    planStartDate: '2025-12-01',
    planEndDate: '2026-11-30',
    totalBudget: 54000,
    allocatedBudget: 48000,
    spentBudget: 38200,
    primaryPractitionerId: 'prac-201',
    primaryPractitionerName: 'Dr. Sarah Jenkins',
    riskLevel: 'High',
    emergencyContact: {
      name: 'Clare McKenzie',
      relationship: 'Mother',
      phone: '0402 114 990'
    },
    restrictivePracticesActive: true,
    createdAt: '2025-12-01T08:00:00Z',
    updatedAt: '2026-09-24T12:00:00Z'
  },
  {
    id: 'cli-titan-tai',
    ndisNumber: '436781290',
    name: 'Titan Tai',
    dateOfBirth: '2010-07-19',
    status: 'Active',
    primaryDisability: 'Autism Spectrum Disorder (Level 3)',
    secondaryDisabilities: ['Severe Behaviours of Concern', 'High Sensory Reactivity'],
    isCompanyDriveParticipant: true,
    driveFolderPath: 'Staff Share Drive > Participants > Behaviour Support > Titan Tai',
    driveFolderUrl: 'https://drive.google.com/drive/u/1/folders/1jd5KeDWRr2-TitanTai',
    driveSubfolders: STANDARD_DRIVE_SUBFOLDERS,
    goals: [
      {
        id: 'g-tit-1',
        title: 'Reduce physical aggression and property destruction through high-density antecedent manipulation',
        category: 'Capacity Building',
        targetDate: '2026-12-15',
        progressPercent: 68,
        status: 'In Progress',
        gasScore: 1
      }
    ],
    planStartDate: '2026-01-01',
    planEndDate: '2026-12-31',
    totalBudget: 78000,
    allocatedBudget: 72000,
    spentBudget: 42100,
    primaryPractitionerId: 'prac-202',
    primaryPractitionerName: 'Marcus Vance',
    riskLevel: 'Critical',
    emergencyContact: {
      name: 'Sione Tai',
      relationship: 'Father',
      phone: '0434 556 789'
    },
    restrictivePracticesActive: true,
    createdAt: '2026-01-01T09:00:00Z',
    updatedAt: '2026-09-25T11:20:00Z'
  },
  {
    id: 'cli-james-enright',
    ndisNumber: '437890123',
    name: 'James Enright',
    dateOfBirth: '1999-05-10',
    status: 'Active',
    primaryDisability: 'Acquired Brain Injury (ABI)',
    secondaryDisabilities: ['Executive Functioning Impairment', 'Frustration Intolerance'],
    isCompanyDriveParticipant: true,
    driveFolderPath: 'Staff Share Drive > Participants > Behaviour Support > James Enright',
    driveFolderUrl: 'https://drive.google.com/drive/u/1/folders/1jd5KeDWRr2-JamesEnright',
    driveSubfolders: STANDARD_DRIVE_SUBFOLDERS,
    goals: [
      {
        id: 'g-enr-1',
        title: 'Increase vocational routine stamina and self-advocacy communication in supported workplace',
        category: 'Capacity Building',
        targetDate: '2026-11-30',
        progressPercent: 64,
        status: 'In Progress',
        gasScore: 0
      }
    ],
    planStartDate: '2026-03-15',
    planEndDate: '2027-03-14',
    totalBudget: 51000,
    allocatedBudget: 46000,
    spentBudget: 19400,
    primaryPractitionerId: 'prac-201',
    primaryPractitionerName: 'Dr. Sarah Jenkins',
    riskLevel: 'High',
    emergencyContact: {
      name: 'Hannah Enright',
      relationship: 'Sister & Nominee',
      phone: '0411 909 332'
    },
    restrictivePracticesActive: true,
    createdAt: '2026-03-15T08:30:00Z',
    updatedAt: '2026-09-17T14:40:00Z'
  },
  {
    id: 'cli-isaiah-farrugia-borg',
    ndisNumber: '438901234',
    name: 'Isaiah Farrugia-Borg',
    dateOfBirth: '2008-02-17',
    status: 'Active',
    primaryDisability: 'Intellectual Disability (Mild)',
    secondaryDisabilities: ['Severe Separation Anxiety', 'School Refusal Behaviours'],
    isCompanyDriveParticipant: true,
    driveFolderPath: 'Staff Share Drive > Participants > Behaviour Support > Isaiah Farrugia-Borg',
    driveFolderUrl: 'https://drive.google.com/drive/u/1/folders/1jd5KeDWRr2-IsaiahFarrugiaBorg',
    driveSubfolders: STANDARD_DRIVE_SUBFOLDERS,
    goals: [
      {
        id: 'g-isa-1',
        title: 'Graduated re-engagement program with structured morning predictability rituals',
        category: 'Capacity Building',
        targetDate: '2026-12-10',
        progressPercent: 55,
        status: 'In Progress',
        gasScore: 0
      }
    ],
    planStartDate: '2026-02-01',
    planEndDate: '2027-01-31',
    totalBudget: 44000,
    allocatedBudget: 39000,
    spentBudget: 17200,
    primaryPractitionerId: 'prac-202',
    primaryPractitionerName: 'Marcus Vance',
    riskLevel: 'Medium',
    emergencyContact: {
      name: 'Tanya Farrugia',
      relationship: 'Mother',
      phone: '0420 887 654'
    },
    restrictivePracticesActive: false,
    createdAt: '2026-02-01T09:30:00Z',
    updatedAt: '2026-09-16T16:15:00Z'
  },
  {
    id: 'cli-harley-roy',
    ndisNumber: '439012345',
    name: 'Harley Roy',
    dateOfBirth: '2013-10-08',
    status: 'Active',
    primaryDisability: 'Autism Spectrum Disorder (Level 2)',
    secondaryDisabilities: ['Selective Mutism', 'Auditory Sensitivity'],
    isCompanyDriveParticipant: true,
    driveFolderPath: 'Staff Share Drive > Participants > Behaviour Support > Harley Roy',
    driveFolderUrl: 'https://drive.google.com/drive/u/1/folders/1jd5KeDWRr2-HarleyRoy',
    driveSubfolders: STANDARD_DRIVE_SUBFOLDERS,
    goals: [
      {
        id: 'g-har-1',
        title: 'Foster low-pressure expressive communication avenues and noise-dampening self-advocacy',
        category: 'Core',
        targetDate: '2026-11-15',
        progressPercent: 80,
        status: 'In Progress',
        gasScore: 1
      }
    ],
    planStartDate: '2026-01-01',
    planEndDate: '2026-12-31',
    totalBudget: 38000,
    allocatedBudget: 34000,
    spentBudget: 14900,
    primaryPractitionerId: 'prac-201',
    primaryPractitionerName: 'Dr. Sarah Jenkins',
    riskLevel: 'Low',
    emergencyContact: {
      name: 'Nathan Roy',
      relationship: 'Father',
      phone: '0415 678 901'
    },
    restrictivePracticesActive: false,
    createdAt: '2026-01-01T08:00:00Z',
    updatedAt: '2026-09-19T10:00:00Z'
  },
  {
    id: 'cli-tyson-gilson',
    ndisNumber: '440123456',
    name: 'Tyson Gilson',
    dateOfBirth: '2003-08-30',
    status: 'Active',
    primaryDisability: 'Down Syndrome',
    secondaryDisabilities: ['Expressive Communication Delay', 'Sensory Fatigue'],
    isCompanyDriveParticipant: true,
    driveFolderPath: 'Staff Share Drive > Participants > Behaviour Support > Tyson Gilson',
    driveFolderUrl: 'https://drive.google.com/drive/u/1/folders/1jd5KeDWRr2-TysonGilson',
    driveSubfolders: STANDARD_DRIVE_SUBFOLDERS,
    goals: [
      {
        id: 'g-tys-1',
        title: 'Support independent choice-making and vocational recreation participation in local community',
        category: 'Social & Community',
        targetDate: '2026-12-31',
        progressPercent: 70,
        status: 'In Progress',
        gasScore: 1
      }
    ],
    planStartDate: '2025-10-15',
    planEndDate: '2026-10-14',
    totalBudget: 46000,
    allocatedBudget: 41000,
    spentBudget: 32400,
    primaryPractitionerId: 'prac-202',
    primaryPractitionerName: 'Marcus Vance',
    riskLevel: 'Medium',
    emergencyContact: {
      name: 'Brenda Gilson',
      relationship: 'Mother',
      phone: '0432 109 876'
    },
    restrictivePracticesActive: false,
    createdAt: '2025-10-15T09:00:00Z',
    updatedAt: '2026-09-20T12:00:00Z'
  },
  {
    id: 'cli-abu-bakr-amiri',
    ndisNumber: '441234567',
    name: 'Abu Bakr Tyson Amiri',
    dateOfBirth: '2005-04-22',
    status: 'Active',
    primaryDisability: 'Autism Spectrum Disorder (Level 3)',
    secondaryDisabilities: ['Severe Agitation during Unstructured Time', 'Property Damage Risk'],
    isCompanyDriveParticipant: true,
    driveFolderPath: 'Staff Share Drive > Participants > Behaviour Support > Abu Bakr Tyson Amiri',
    driveFolderUrl: 'https://drive.google.com/drive/u/1/folders/1jd5KeDWRr2-AbuBakrTysonAmiri',
    driveSubfolders: STANDARD_DRIVE_SUBFOLDERS,
    goals: [
      {
        id: 'g-abu-1',
        title: 'Train support staff in consistent positive reinforcement and sensory schedule implementation',
        category: 'Capacity Building',
        targetDate: '2026-12-20',
        progressPercent: 74,
        status: 'In Progress',
        gasScore: 1
      }
    ],
    planStartDate: '2026-01-10',
    planEndDate: '2027-01-09',
    totalBudget: 71000,
    allocatedBudget: 65000,
    spentBudget: 34100,
    primaryPractitionerId: 'prac-201',
    primaryPractitionerName: 'Dr. Sarah Jenkins',
    riskLevel: 'High',
    emergencyContact: {
      name: 'Ahmad Amiri',
      relationship: 'Brother & Primary Nominee',
      phone: '0421 789 012'
    },
    restrictivePracticesActive: true,
    createdAt: '2026-01-10T08:30:00Z',
    updatedAt: '2026-09-23T15:00:00Z'
  },
  {
    id: 'cli-celeste-rattray-wood',
    ndisNumber: '442345678',
    name: 'Celeste Rattray-Wood',
    dateOfBirth: '2001-11-14',
    status: 'Active',
    primaryDisability: 'Cerebral Palsy (Spastic Quadriplegia)',
    secondaryDisabilities: ['Expressive Dysphasia', 'Discomfort-Related Agitation'],
    isCompanyDriveParticipant: true,
    driveFolderPath: 'Staff Share Drive > Participants > Behaviour Support > Celeste Rattray-Wood',
    driveFolderUrl: 'https://drive.google.com/drive/u/1/folders/1jd5KeDWRr2-CelesteRattrayWood',
    driveSubfolders: STANDARD_DRIVE_SUBFOLDERS,
    goals: [
      {
        id: 'g-cel-1',
        title: 'Optimize environmental controls and non-verbal pain-signaling system for direct care staff',
        category: 'Capacity Building',
        targetDate: '2026-12-15',
        progressPercent: 68,
        status: 'In Progress',
        gasScore: 1
      }
    ],
    planStartDate: '2026-02-01',
    planEndDate: '2027-01-31',
    totalBudget: 56000,
    allocatedBudget: 50000,
    spentBudget: 22800,
    primaryPractitionerId: 'prac-202',
    primaryPractitionerName: 'Marcus Vance',
    riskLevel: 'Medium',
    emergencyContact: {
      name: 'Wendy Rattray',
      relationship: 'Mother',
      phone: '0414 223 344'
    },
    restrictivePracticesActive: false,
    createdAt: '2026-02-01T09:00:00Z',
    updatedAt: '2026-09-21T11:30:00Z'
  },
  {
    id: 'cli-viren-virdi',
    ndisNumber: '443456789',
    name: 'Viren Virdi',
    dateOfBirth: '2009-07-01',
    status: 'Active',
    primaryDisability: 'Autism Spectrum Disorder (Level 2)',
    secondaryDisabilities: ['Rigid Behavioural Routines', 'Extreme School Anxiety'],
    isCompanyDriveParticipant: true,
    driveFolderPath: 'Staff Share Drive > Participants > Behaviour Support > Viren Virdi',
    driveFolderUrl: 'https://drive.google.com/drive/u/1/folders/1jd5KeDWRr2-VirenVirdi',
    driveSubfolders: STANDARD_DRIVE_SUBFOLDERS,
    goals: [
      {
        id: 'g-vir-1',
        title: 'Gradually increase cognitive flexibility during changes in daily schedule via visual countdowns',
        category: 'Capacity Building',
        targetDate: '2026-11-30',
        progressPercent: 61,
        status: 'In Progress',
        gasScore: 0
      }
    ],
    planStartDate: '2026-01-15',
    planEndDate: '2027-01-14',
    totalBudget: 47000,
    allocatedBudget: 42000,
    spentBudget: 18900,
    primaryPractitionerId: 'prac-201',
    primaryPractitionerName: 'Dr. Sarah Jenkins',
    riskLevel: 'Medium',
    emergencyContact: {
      name: 'Harpreet Virdi',
      relationship: 'Mother',
      phone: '0405 667 889'
    },
    restrictivePracticesActive: false,
    createdAt: '2026-01-15T08:00:00Z',
    updatedAt: '2026-09-19T13:45:00Z'
  },
  {
    id: 'cli-selena-ajak',
    ndisNumber: '444567890',
    name: 'Selena Ajak',
    dateOfBirth: '2007-09-19',
    status: 'Active',
    primaryDisability: 'Complex Developmental Trauma / Developmental Delay',
    secondaryDisabilities: ['Hypervigilance', 'Fight-or-Flight Escalations'],
    isCompanyDriveParticipant: true,
    driveFolderPath: 'Staff Share Drive > Participants > Behaviour Support > Selena Ajak',
    driveFolderUrl: 'https://drive.google.com/drive/u/1/folders/1jd5KeDWRr2-SelenaAjak',
    driveSubfolders: STANDARD_DRIVE_SUBFOLDERS,
    goals: [
      {
        id: 'g-sel-1',
        title: 'Establish relational safety cues and distress co-regulation routines with key support workers',
        category: 'Capacity Building',
        targetDate: '2026-12-31',
        progressPercent: 73,
        status: 'In Progress',
        gasScore: 1
      }
    ],
    planStartDate: '2026-02-10',
    planEndDate: '2027-02-09',
    totalBudget: 60000,
    allocatedBudget: 54000,
    spentBudget: 24700,
    primaryPractitionerId: 'prac-201',
    primaryPractitionerName: 'Dr. Sarah Jenkins',
    riskLevel: 'High',
    emergencyContact: {
      name: 'Deng Ajak',
      relationship: 'Nominee / Support Guardian',
      phone: '0422 998 112'
    },
    restrictivePracticesActive: true,
    createdAt: '2026-02-10T09:30:00Z',
    updatedAt: '2026-09-22T14:10:00Z'
  }
];

export const INITIAL_CLIENTS: Client[] = [
  ...COMPANY_DRIVE_PARTICIPANTS,
  {
    id: 'cli-101',
    ndisNumber: '430891245',
    name: 'Jordan Miller',
    dateOfBirth: '2004-03-15',
    status: 'Active',
    primaryDisability: 'Autism Spectrum Disorder (Level 3)',
    secondaryDisabilities: ['Generalized Anxiety Disorder', 'Sensory Processing Sensitivity'],
    goals: [
      {
        id: 'g-101',
        title: 'Master independent emotional regulation techniques during sensory overload in community environments',
        category: 'Capacity Building',
        targetDate: '2026-12-31',
        progressPercent: 68,
        status: 'In Progress',
        gasScore: 1,
        gasHistory: [
          { date: '2026-01-10', score: -1, note: 'Baseline assessed with high escalation triggers' },
          { date: '2026-04-15', score: 0, note: 'Sensory breaks successfully introduced' },
          { date: '2026-07-20', score: 1, note: 'Independent use of visual noise dampening cues' }
        ]
      },
      {
        id: 'g-102',
        title: 'Establish routine functional communication system for daily preferences',
        category: 'Core',
        targetDate: '2026-10-31',
        progressPercent: 82,
        status: 'In Progress',
        gasScore: 1
      }
    ],
    planStartDate: '2026-01-01',
    planEndDate: '2026-12-31',
    totalBudget: 48500,
    allocatedBudget: 42000,
    spentBudget: 24350,
    primaryPractitionerId: 'prac-202',
    primaryPractitionerName: 'Marcus Vance',
    riskLevel: 'Medium',
    emergencyContact: {
      name: 'Karen Miller',
      relationship: 'Mother & Primary Nominee',
      phone: '0412 889 201'
    },
    restrictivePracticesActive: true,
    createdAt: '2026-01-01T08:00:00Z',
    updatedAt: '2026-08-10T14:30:00Z'
  },
  {
    id: 'cli-102',
    ndisNumber: '431092841',
    name: 'Samantha Reed',
    dateOfBirth: '1998-11-22',
    status: 'Active',
    primaryDisability: 'Acquired Brain Injury (ABI)',
    secondaryDisabilities: ['Executive Function Impairment'],
    goals: [
      {
        id: 'g-103',
        title: 'Increase vocational routine tolerance with visual schedule prompting',
        category: 'Social & Community',
        targetDate: '2026-11-30',
        progressPercent: 55,
        status: 'In Progress',
        gasScore: 0
      }
    ],
    planStartDate: '2026-02-15',
    planEndDate: '2027-02-14',
    totalBudget: 36000,
    allocatedBudget: 31000,
    spentBudget: 15400,
    primaryPractitionerId: 'prac-201',
    primaryPractitionerName: 'Dr. Sarah Jenkins',
    riskLevel: 'Low',
    emergencyContact: {
      name: 'David Reed',
      relationship: 'Brother / Support Nominee',
      phone: '0433 112 904'
    },
    restrictivePracticesActive: false,
    createdAt: '2026-02-15T09:00:00Z',
    updatedAt: '2026-08-08T11:20:00Z'
  },
  {
    id: 'cli-103',
    ndisNumber: '439901422',
    name: 'Liam O’Connor',
    dateOfBirth: '2010-06-04',
    status: 'Active',
    primaryDisability: 'Intellectual Disability (Moderate)',
    secondaryDisabilities: ['ADHD - Combined Type'],
    goals: [
      {
        id: 'g-104',
        title: 'Reduce behavioral escalations in classroom settings through sensory breaks',
        category: 'Capacity Building',
        targetDate: '2026-12-15',
        progressPercent: 40,
        status: 'In Progress',
        gasScore: -1
      }
    ],
    planStartDate: '2025-10-01',
    planEndDate: '2026-09-30',
    totalBudget: 55000,
    allocatedBudget: 50000,
    spentBudget: 39800,
    primaryPractitionerId: 'prac-202',
    primaryPractitionerName: 'Marcus Vance',
    riskLevel: 'High',
    emergencyContact: {
      name: 'Sean O’Connor',
      relationship: 'Father',
      phone: '0409 778 123'
    },
    restrictivePracticesActive: true,
    createdAt: '2025-10-01T08:30:00Z',
    updatedAt: '2026-08-12T16:00:00Z'
  }
];

export const INITIAL_PRACTITIONERS: Practitioner[] = [
  {
    id: 'prac-201',
    name: 'Dr. Sarah Jenkins',
    email: 'sarah.jenkins@breakthrough.org.au',
    phone: '0411 234 567',
    position: 'Senior Behaviour Support Practitioner',
    qualification: 'PhD Clinical Psychology, MAPS, NDIS Advanced PBS',
    ndisRegistrationNumber: 'PRAC-NDIS-08819',
    pbsRegistrationLevel: 'Advanced Practitioner',
    specialties: ['Complex Behaviour Support', 'Restrictive Practice Reduction', 'Neurodiversity'],
    status: 'Active',
    workerScreeningNumber: 'NDIS-WSC-9908124',
    workerScreeningExpiry: '2028-09-30',
    wwccNumber: 'WWC0981724E',
    wwccExpiry: '2028-09-30',
    screeningStatus: 'Valid',
    screeningExpiryDate: '2028-09-30',
    policeCheckExpiryDate: '2027-11-15',
    cprExpiryDate: '2027-04-10',
    firstAidExpiryDate: '2027-04-10',
    medicationCertExpiryDate: '2027-08-15',
    mandatoryTrainingExpiryDate: '2027-02-01',
    ndisOrientationCompleted: true,
    cpdHoursThisYear: 38,
    cpdHoursRequired: 30,
    caseloadLimit: 20,
    activeCaseloadCount: 14,
    historicalSuccessRate: 94,
    completedSessionsCount: 420,
    rating: 4.9
  },
  {
    id: 'prac-202',
    name: 'Marcus Vance',
    email: 'marcus.vance@breakthrough.org.au',
    phone: '0422 345 678',
    position: 'Senior Behaviour Support Practitioner',
    qualification: 'Master of Applied Behaviour Analysis, BCBA',
    ndisRegistrationNumber: 'PRAC-NDIS-07742',
    pbsRegistrationLevel: 'Proficient Practitioner',
    specialties: ['Autism Spectrum Disorder', 'Functional Behaviour Assessments', 'Staff Coaching'],
    status: 'Active',
    workerScreeningNumber: 'NDIS-WSC-7718290',
    workerScreeningExpiry: '2027-05-12',
    wwccNumber: 'WWC0876123V',
    wwccExpiry: '2027-05-12',
    screeningStatus: 'Valid',
    screeningExpiryDate: '2027-05-12',
    policeCheckExpiryDate: '2026-10-20',
    cprExpiryDate: '2026-09-15',
    firstAidExpiryDate: '2026-09-15',
    medicationCertExpiryDate: '2026-08-28',
    mandatoryTrainingExpiryDate: '2026-09-10',
    ndisOrientationCompleted: true,
    cpdHoursThisYear: 26,
    cpdHoursRequired: 30,
    caseloadLimit: 22,
    activeCaseloadCount: 18,
    historicalSuccessRate: 91,
    completedSessionsCount: 512,
    rating: 4.8
  },
  {
    id: 'prac-203',
    name: 'Elena Rostova',
    email: 'elena.rostova@breakthrough.org.au',
    phone: '0433 456 789',
    position: 'Occupational Therapist',
    qualification: 'Bachelor of Occupational Therapy (Hons), AHPRA',
    ndisRegistrationNumber: 'PRAC-NDIS-09124',
    pbsRegistrationLevel: 'Core Practitioner',
    specialties: ['Sensory Modulation', 'Ergonomic Environments', 'Capacity Assessment'],
    status: 'Active',
    workerScreeningNumber: 'NDIS-WSC-5529184',
    workerScreeningExpiry: '2028-01-14',
    wwccNumber: 'WWC0745912E',
    wwccExpiry: '2028-01-14',
    screeningStatus: 'Valid',
    screeningExpiryDate: '2028-01-14',
    policeCheckExpiryDate: '2027-06-30',
    cprExpiryDate: '2027-03-20',
    firstAidExpiryDate: '2027-03-20',
    medicationCertExpiryDate: '2027-05-18',
    mandatoryTrainingExpiryDate: '2027-01-15',
    ndisOrientationCompleted: true,
    cpdHoursThisYear: 31,
    cpdHoursRequired: 30,
    caseloadLimit: 18,
    activeCaseloadCount: 12,
    historicalSuccessRate: 96,
    completedSessionsCount: 340,
    rating: 4.9
  },
  {
    id: 'prac-204',
    name: 'Sarah Davies',
    email: 'sarah.davies@breakthrough.org.au',
    phone: '0444 567 890',
    position: 'Lead Support Coordinator & Intake Specialist',
    qualification: 'Bachelor of Social Work (AASW), Cert IV Disability',
    ndisRegistrationNumber: 'PRAC-NDIS-06651',
    pbsRegistrationLevel: 'Support Coordinator',
    specialties: ['Complex Intake', 'Plan Re-assessments', 'Emergency Crisis Navigation'],
    status: 'Active',
    workerScreeningNumber: 'NDIS-WSC-3391820',
    workerScreeningExpiry: '2027-11-20',
    wwccNumber: 'WWC0551928V',
    wwccExpiry: '2027-11-20',
    screeningStatus: 'Valid',
    screeningExpiryDate: '2027-11-20',
    policeCheckExpiryDate: '2026-12-15',
    cprExpiryDate: '2026-11-05',
    firstAidExpiryDate: '2026-11-05',
    medicationCertExpiryDate: '2027-01-20',
    mandatoryTrainingExpiryDate: '2026-11-15',
    ndisOrientationCompleted: true,
    cpdHoursThisYear: 34,
    cpdHoursRequired: 30,
    caseloadLimit: 25,
    activeCaseloadCount: 22,
    historicalSuccessRate: 93,
    completedSessionsCount: 610,
    rating: 4.8
  }
];

export const INITIAL_RESTRICTIVE_PRACTICES: RestrictivePractice[] = [
  {
    id: 'rp-301',
    clientId: 'cli-101',
    clientName: 'Jordan Miller',
    practiceType: 'Environmental',
    description: 'Locked kitchen pantry containing high-sugar sensory items outside scheduled snack periods',
    status: 'Authorized',
    authorizationBody: 'Victorian Senior Practitioner Panel',
    authorizationReference: 'VSP-AUTH-2026-8819',
    startDate: '2026-02-01',
    expiryDate: '2027-01-31',
    reductionPlanSummary: 'Graduated visual food choice cards and self-monitoring schedule to fade lock dependency by Q4 2026.',
    monthlyReportStatus: 'Submitted',
    lastReportedDate: '2026-08-01'
  },
  {
    id: 'rp-302',
    clientId: 'cli-103',
    clientName: 'Liam O’Connor',
    practiceType: 'Chemical',
    description: 'Low-dose Clonidine (0.05mg) as prescribed by paediatrician for acute autonomic arousal with extreme self-injury risk',
    status: 'Authorized',
    authorizationBody: 'NDIS Quality & Safeguards Commission State Authorizer',
    authorizationReference: 'NDIS-RP-2026-0441',
    startDate: '2026-03-15',
    expiryDate: '2026-09-14',
    reductionPlanSummary: 'Multi-sensory deep pressure protocol implemented 15 mins prior to transition triggers to reduce PRN administration by 50%.',
    monthlyReportStatus: 'Due',
    lastReportedDate: '2026-07-28'
  }
];

export const INITIAL_INCIDENTS: Incident[] = [
  {
    id: 'inc-400',
    clientId: 'cli-101',
    clientName: 'Jordan Miller',
    practitionerId: 'prac-201',
    practitionerName: 'Dr. Sarah Jenkins',
    incidentDate: '2026-08-16T14:10:00Z',
    severity: 'Critical / Reportable',
    status: 'Investigating',
    isNdisReportable: true,
    ndis24hrNotified: true,
    ndis5daySubmitted: false,
    description: 'Participant demonstrated intense acute agitation with unexpected physical strike during community therapy transition, requiring 30-sec emergency guide.',
    immediateActionTaken: 'Staff initiated positive de-escalation protocol level 3; participant guided to low-stimulus vehicle; 24-hr Commission notice lodged.',
    rootCauseAnalysis: 'Sensory overload combined with sudden transport delay; formal 5-day root cause investigation pending.',
    correctiveActions: 'Reviewing transport schedule buffer times; updated proactive sensory transition kit in progress.',
    reportedBy: 'Dr. Sarah Jenkins',
    createdAt: '2026-08-16T14:10:00Z'
  },
  {
    id: 'inc-401',
    clientId: 'cli-103',
    clientName: 'Liam O’Connor',
    practitionerId: 'prac-202',
    practitionerName: 'Marcus Vance',
    incidentDate: '2026-08-14T10:15:00Z',
    severity: 'Medium',
    status: 'Closed',
    isNdisReportable: false,
    ndis24hrNotified: false,
    ndis5daySubmitted: false,
    description: 'Verbal agitation and thrown plastic cup during sensory transition at day program. No physical contact or injury.',
    immediateActionTaken: 'Practitioner guided participant to quiet sensory decompression corner; offered noise-canceling headphones.',
    rootCauseAnalysis: 'Unannounced fire alarm testing in adjacent suite triggered unexpected sensory hyper-reactivity.',
    correctiveActions: 'Day program coordination protocol established to provide 30-minute advance written notification for all facility auditory tests.',
    reportedBy: 'Marcus Vance',
    createdAt: '2026-08-14T10:15:00Z'
  },
  {
    id: 'inc-402',
    clientId: 'cli-101',
    clientName: 'Jordan Miller',
    practitionerId: 'prac-201',
    practitionerName: 'Dr. Sarah Jenkins',
    incidentDate: '2026-08-02T16:30:00Z',
    severity: 'Low',
    status: 'Resolved',
    isNdisReportable: false,
    ndis24hrNotified: false,
    ndis5daySubmitted: false,
    description: 'Minor refusal during transition from sensory swing to tabletop activity.',
    immediateActionTaken: 'Visual timer reset for additional 3 minutes followed by successful transition.',
    reportedBy: 'Dr. Sarah Jenkins',
    createdAt: '2026-08-02T16:30:00Z'
  },
  {
    id: 'inc-403',
    clientId: 'cli-102',
    clientName: 'Samantha Reed',
    practitionerId: 'prac-202',
    practitionerName: 'Marcus Vance',
    incidentDate: '2026-07-22T14:45:00Z',
    severity: 'Critical / Reportable',
    status: 'Closed',
    isNdisReportable: true,
    ndis24hrNotified: true,
    ndis5daySubmitted: true,
    description: 'Severe escalation resulting in self-injurious head banging during crowded shopping mall therapy outing.',
    immediateActionTaken: 'Participant escorted to quiet parent vehicle immediately, sensory compression applied, 24-hr NDIS Commission notification lodged.',
    reportedBy: 'Marcus Vance',
    createdAt: '2026-07-22T14:45:00Z'
  },
  {
    id: 'inc-404',
    clientId: 'cli-103',
    clientName: 'Liam O’Connor',
    practitionerId: 'prac-203',
    practitionerName: 'Elena Rostova',
    incidentDate: '2026-07-11T11:20:00Z',
    severity: 'High',
    status: 'Resolved',
    isNdisReportable: false,
    ndis24hrNotified: false,
    ndis5daySubmitted: false,
    description: 'Property damage during sensory overload in communal dining area.',
    immediateActionTaken: 'Staff cleared area and offered weighted lap blanket and low-stimulus room.',
    reportedBy: 'Elena Rostova',
    createdAt: '2026-07-11T11:20:00Z'
  },
  {
    id: 'inc-405',
    clientId: 'cli-101',
    clientName: 'Jordan Miller',
    practitionerId: 'prac-202',
    practitionerName: 'Marcus Vance',
    incidentDate: '2026-06-18T15:10:00Z',
    severity: 'High',
    status: 'Closed',
    isNdisReportable: false,
    ndis24hrNotified: false,
    ndis5daySubmitted: false,
    description: 'High-intensity vocal outburst and kicking therapy partition during schedule delay.',
    immediateActionTaken: 'Practitioner deployed first-then visual sequence and calming music.',
    reportedBy: 'Marcus Vance',
    createdAt: '2026-06-18T15:10:00Z'
  },
  {
    id: 'inc-406',
    clientId: 'cli-102',
    clientName: 'Samantha Reed',
    practitionerId: 'prac-201',
    practitionerName: 'Dr. Sarah Jenkins',
    incidentDate: '2026-05-29T17:00:00Z',
    severity: 'Critical / Reportable',
    status: 'Closed',
    isNdisReportable: true,
    ndis24hrNotified: true,
    ndis5daySubmitted: true,
    description: 'Emergency physical hold applied for 45 seconds to prevent participant from running towards high-traffic roadway.',
    immediateActionTaken: 'Safety secured, emergency debrief conducted, restrictive practice reported to NDIS Commission within 24 hours.',
    reportedBy: 'Dr. Sarah Jenkins',
    createdAt: '2026-05-29T17:00:00Z'
  },
  {
    id: 'inc-407',
    clientId: 'cli-103',
    clientName: 'Liam O’Connor',
    practitionerId: 'prac-203',
    practitionerName: 'Elena Rostova',
    incidentDate: '2026-05-14T09:40:00Z',
    severity: 'Medium',
    status: 'Resolved',
    isNdisReportable: false,
    ndis24hrNotified: false,
    ndis5daySubmitted: false,
    description: 'Sensory dysregulation during speech therapy assessment session.',
    immediateActionTaken: 'Deep pressure proprioceptive exercises provided.',
    reportedBy: 'Elena Rostova',
    createdAt: '2026-05-14T09:40:00Z'
  },
  {
    id: 'inc-408',
    clientId: 'cli-101',
    clientName: 'Jordan Miller',
    practitionerId: 'prac-202',
    practitionerName: 'Marcus Vance',
    incidentDate: '2026-04-20T13:15:00Z',
    severity: 'Low',
    status: 'Closed',
    isNdisReportable: false,
    ndis24hrNotified: false,
    ndis5daySubmitted: false,
    description: 'Mild anxiety manifestation prior to community transport boarding.',
    immediateActionTaken: 'Social story reviewed with participant.',
    reportedBy: 'Marcus Vance',
    createdAt: '2026-04-20T13:15:00Z'
  },
  {
    id: 'inc-409',
    clientId: 'cli-102',
    clientName: 'Samantha Reed',
    practitionerId: 'prac-201',
    practitionerName: 'Dr. Sarah Jenkins',
    incidentDate: '2026-03-12T16:20:00Z',
    severity: 'High',
    status: 'Closed',
    isNdisReportable: false,
    ndis24hrNotified: false,
    ndis5daySubmitted: false,
    description: 'Intense aggression toward support equipment after unexpected routine alteration.',
    immediateActionTaken: 'Positive Behaviour Support de-escalation protocol level 2 initiated.',
    reportedBy: 'Dr. Sarah Jenkins',
    createdAt: '2026-03-12T16:20:00Z'
  },
  {
    id: 'inc-410',
    clientId: 'cli-103',
    clientName: 'Liam O’Connor',
    practitionerId: 'prac-202',
    practitionerName: 'Marcus Vance',
    incidentDate: '2026-02-18T10:05:00Z',
    severity: 'Medium',
    status: 'Closed',
    isNdisReportable: false,
    ndis24hrNotified: false,
    ndis5daySubmitted: false,
    description: 'Refusal and verbal protest during gross motor therapy session.',
    immediateActionTaken: 'Alternative choice of therapy equipment offered.',
    reportedBy: 'Marcus Vance',
    createdAt: '2026-02-18T10:05:00Z'
  },
  {
    id: 'inc-411',
    clientId: 'cli-101',
    clientName: 'Jordan Miller',
    practitionerId: 'prac-201',
    practitionerName: 'Dr. Sarah Jenkins',
    incidentDate: '2026-01-25T14:30:00Z',
    severity: 'High',
    status: 'Closed',
    isNdisReportable: false,
    ndis24hrNotified: false,
    ndis5daySubmitted: false,
    description: 'Severe sensory meltdown upon return from extended holiday break.',
    immediateActionTaken: 'Quiet room decompression protocol executed with low lighting and deep pressure vest.',
    reportedBy: 'Dr. Sarah Jenkins',
    createdAt: '2026-01-25T14:30:00Z'
  }
];

export const INITIAL_CASE_NOTES: CaseNote[] = [
  {
    id: 'note-001',
    clientId: 'cli-001',
    clientName: 'Sarah Jenkins',
    practitionerId: 'prac-202',
    practitionerName: 'Marcus Vance',
    date: '2026-09-02',
    sessionDurationMinutes: 60,
    nonFaceToFaceMinutes: 15,
    format: 'SOAP',
    category: 'NDIS Plan Review & Goal Realignment',
    subjective: 'Participant and support coordinator reviewed latest NDIA plan extension goals. Expressed desire for continued hydrotherapy.',
    objective: 'Verified Google Drive official NDIS Plan documentation. Cross-referenced line items against Section 34 criteria.',
    assessment: 'Participant capacity building budget is adequately provisioned for 12 months. Goal progression targets met.',
    plan: 'Submit clinical progress summary to planner; arrange multidisciplinary case conference.',
    linkedGoalIds: ['g-001'],
    linkedDocumentIds: ['gdoc-1'],
    linkedDriveFiles: [
      {
        id: 'gdoc-1',
        driveFileId: '1BxiMVs0XRA5nFMdKvBdBZjgmUUqptlbs74OgvE2upms',
        name: 'Sarah Jenkins - NDIS Plan 2026-2027 (Official NDIA).pdf',
        mimeType: 'application/pdf',
        url: 'https://drive.google.com/file/d/1BxiMVs0XRA5nFMdKvBdBZjgmUUqptlbs74OgvE2upms/view',
        sizeBytes: 1845200,
        category: 'NDIS Plan Document',
        tags: ['Clinical', 'Financial'],
        uploadedAt: '2026-09-02T10:00:00Z'
      }
    ],
    status: 'Approved',
    flaggedForReview: false,
    createdAt: '2026-09-02T10:00:00Z',
    updatedAt: '2026-09-02T10:30:00Z'
  },
  {
    id: 'note-002',
    clientId: 'cli-002',
    clientName: 'Michael Chang',
    practitionerId: 'prac-202',
    practitionerName: 'Marcus Vance',
    date: '2026-09-04',
    sessionDurationMinutes: 75,
    nonFaceToFaceMinutes: 30,
    format: 'BIRP',
    category: 'Behaviour Support Plan Review',
    subjective: 'Support staff reported reduced target behaviors during sensory transitions in morning routines.',
    objective: 'Evaluated functional behavior assessments in attached Drive document. Observed positive engagement with AAC device.',
    assessment: 'Proactive de-escalation strategies outlined in Level 3 PBS are being consistently applied by household staff.',
    plan: 'Update PBS document in Google Drive; schedule staff training module for next Tuesday.',
    linkedGoalIds: ['g-002'],
    linkedDocumentIds: ['gdoc-2'],
    linkedDriveFiles: [
      {
        id: 'gdoc-2',
        driveFileId: '1gJ_4s9jE24YfU8Qz7B0xP9aT1LmN3kRt',
        name: 'Michael Chang - Comprehensive Functional Behaviour Assessment (PBS Level 3).docx',
        mimeType: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
        url: 'https://drive.google.com/file/d/1gJ_4s9jE24YfU8Qz7B0xP9aT1LmN3kRt/view',
        sizeBytes: 945000,
        category: 'Assessment PDF',
        tags: ['Clinical', 'Behavioural'],
        uploadedAt: '2026-09-04T14:00:00Z'
      }
    ],
    status: 'Approved',
    flaggedForReview: false,
    createdAt: '2026-09-04T14:00:00Z',
    updatedAt: '2026-09-04T14:45:00Z'
  },
  {
    id: 'note-501',
    clientId: 'cli-101',
    clientName: 'Jordan Miller',
    practitionerId: 'prac-202',
    practitionerName: 'Marcus Vance',
    date: '2026-08-12',
    sessionDurationMinutes: 90,
    format: 'Standard',
    subjective: 'Participant arrived calm; mother reported two successful community outings this week with zero dysregulation events.',
    objective: 'Practitioner conducted a 45-minute structured functional activity evaluating the newly introduced visual schedule board. Jordan independently initiated 4 communication exchanges using PECS.',
    assessment: 'Participant is demonstrating rapid acquisition of secondary communication pathways. Goal 1.1 progression is on track.',
    plan: 'Deliver 1-hour coaching session with primary support worker on Wednesday; introduce step 2 in sensory regulation binder.',
    linkedGoalIds: ['g-101'],
    status: 'Approved',
    flaggedForReview: false,
    createdAt: '2026-08-12T16:00:00Z',
    updatedAt: '2026-08-12T16:45:00Z'
  }
];

export const INITIAL_LEADS: Lead[] = [
  {
    id: 'lead-601',
    prospectName: 'Ethan Brooks',
    ndisNumber: '439182773',
    contactName: 'Jessica Brooks (Parent)',
    contactEmail: 'jessica.brooks@example.com',
    contactPhone: '0421 990 812',
    stage: 'Service Agreement Pending',
    source: 'Support Coordinator Referral',
    estimatedPlanValue: 42000,
    assignedPractitionerId: 'prac-202',
    assignedPractitionerName: 'Marcus Vance',
    notes: 'Requires Comprehensive Functional Behaviour Assessment and Interim Behaviour Support Plan before October 2026.',
    createdAt: '2026-08-01T09:00:00Z',
    updatedAt: '2026-08-14T11:00:00Z'
  },
  {
    id: 'lead-602',
    prospectName: 'Maya Patel',
    ndisNumber: '438771209',
    contactName: 'Ravi Patel',
    contactEmail: 'ravi.patel@example.com',
    contactPhone: '0432 554 123',
    stage: 'New Intake',
    source: 'Direct Website',
    estimatedPlanValue: 28000,
    assignedPractitionerId: 'prac-201',
    assignedPractitionerName: 'Dr. Sarah Jenkins',
    notes: 'Transition to supported independent living (SIL); requires baseline sensory and communication profile.',
    createdAt: '2026-08-10T14:00:00Z',
    updatedAt: '2026-08-15T08:30:00Z'
  }
];

export const INITIAL_ABC_LOGS: ABCLog[] = [
  {
    id: 'abc-701',
    clientId: 'cli-101',
    clientName: 'Jordan Miller',
    timestamp: '2026-08-13T14:20:00Z',
    timeOfDay: '14:20',
    dayOfWeek: 'Thursday',
    antecedent: 'Transition from iPad video game to dinnertime meal prep in crowded kitchen',
    behavior: 'Vocal protest, dropped to floor, refused to move for 8 minutes',
    consequence: 'Worker provided visual timer giving 3-minute extension; participant stood up calmly when timer chimed',
    intensity: 3,
    durationMinutes: 8,
    location: 'Family Residence - Kitchen',
    perceivedFunction: 'Escape/Avoidance',
    recordedBy: 'Support Worker Dave T.'
  }
];

export const INITIAL_CLAIMS: BillingClaim[] = [
  {
    id: 'claim-801',
    clientId: 'cli-101',
    clientName: 'Jordan Miller',
    ndisNumber: '430891245',
    serviceDate: '2026-08-12',
    ndisSupportItem: 'Specialist Behavioural Intervention Support',
    supportItemCode: '07_002_0115_8_3',
    hours: 1.5,
    unitRate: 214.41,
    totalAmount: 321.62,
    status: 'Approved',
    invoiceNumber: 'INV-BK-2026-0941',
    reconciliationStatus: 'Reconciled',
    slaDeadline: '2026-08-26',
    paymentReceivedDate: '2026-08-14'
  },
  {
    id: 'claim-802',
    clientId: 'cli-102',
    clientName: 'Samantha Reed',
    ndisNumber: '431092841',
    serviceDate: '2026-08-11',
    ndisSupportItem: 'Assessment Recommendation Therapy Support - Allied Health',
    supportItemCode: '15_056_0128_1_3',
    hours: 2.0,
    unitRate: 193.99,
    totalAmount: 387.98,
    status: 'Pending',
    invoiceNumber: 'INV-BK-2026-0942',
    reconciliationStatus: 'SLA_Breach_Risk',
    reconciliationError: 'PACE Submission pending > 5 business days; nearing 7-day payment SLA window',
    slaDeadline: '2026-08-18'
  },
  {
    id: 'claim-803',
    clientId: 'cli-101',
    clientName: 'Jordan Miller',
    ndisNumber: '430891245',
    serviceDate: '2026-08-04',
    ndisSupportItem: 'Individual Behaviour Support Plan Development & Training',
    supportItemCode: '07_004_0115_8_3',
    hours: 3.0,
    unitRate: 235.00,
    totalAmount: 705.00,
    status: 'Rejected',
    invoiceNumber: 'INV-BK-2026-0938',
    reconciliationStatus: 'Failed',
    reconciliationError: 'Unit rate $235.00 exceeds NDIS price cap of $214.41/hr for line item 07_004_0115_8_3',
    slaDeadline: '2026-08-11'
  }
];

export const INITIAL_BSP: BSPDocument = {
  id: 'bsp-main',
  clientId: 'cli-101',
  clientName: 'Jordan Miller',
  version: '2.1',
  status: 'Active',
  summary: 'Comprehensive Positive Behaviour Support Plan focusing on proactive sensory regulation, environmental predictability, and functional communication training.',
  primaryBehaviorsOfConcern: [
    'Sensory overload flight / bolting behaviors during high-decibel community transitions',
    'Intense vocal protesting and task refusal during abrupt activity changes'
  ],
  proactiveStrategies: [
    'Maintain consistent visual scheduling with minimum 5-minute countdown timers prior to all activity transitions',
    'Pre-emptively equip participant with active noise-dampening headphones in busy retail / public transit spaces',
    'Provide structured choice opportunities between two preferred activities every 60 minutes'
  ],
  reactiveStrategies: [
    'Low-arousal verbal de-escalation: reduce vocal volume, speak in short 2-3 word neutral phrases',
    'Create generous physical buffer space; avoid blocking natural exit pathways',
    'Offer familiar calming sensory tools (weighted lap pad, tactile resistance squeeze ball)'
  ],
  restrictivePractices: INITIAL_RESTRICTIVE_PRACTICES,
  reviewDate: '2027-01-31',
  authorName: 'Marcus Vance (Senior PBS Practitioner)',
  lastUpdated: '2026-08-10T14:30:00Z'
};

export const INITIAL_NOTIFICATIONS: AppNotification[] = [
  {
    id: 'notif-1',
    title: 'NDIS Commission Monthly Submission Ready',
    message: 'Monthly restrictive practice summary report for Jordan Miller is due in 16 days.',
    type: 'clinical',
    severity: 'high',
    timestamp: '2026-08-15T08:00:00Z',
    read: false,
    linkTab: 'restrictive-practices'
  },
  {
    id: 'notif-2',
    title: 'Google Workspace Gateway Live',
    message: 'Direct OAuth connected with Google Drive, Sheets, Docs, Calendar, Meet, and Gmail.',
    type: 'compliance',
    severity: 'low',
    timestamp: '2026-08-15T09:30:00Z',
    read: false,
    linkTab: 'google-workspace'
  }
];

export const INITIAL_CRM_TASKS: CRMTask[] = [
  {
    id: 'task-101',
    title: 'Review afternoon de-escalation log with support team',
    description: 'Check Jordan responded to 5-minute visual timer cue card during Tuesday transit.',
    category: 'Clinical',
    priority: 'High',
    status: 'Pending',
    dueDate: '2026-08-22',
    assignedTo: 'Marcus Vance',
    sourceNoteId: 'keep-1',
    sourceNoteTitle: 'Jordan Miller - Sensory De-escalation Protocol',
    clientId: 'cli-101',
    clientName: 'Jordan Miller',
    isSyncedFromKeep: true,
    createdAt: '2026-08-15T09:15:00Z',
    updatedAt: '2026-08-15T09:15:00Z'
  },
  {
    id: 'task-102',
    title: 'Generate monthly incident trend graph for Senior Practitioner',
    description: 'Prepare restrictive practice summary submission reports for Liam O’Connor audit review.',
    category: 'Compliance',
    priority: 'Critical',
    status: 'In Progress',
    dueDate: '2026-08-25',
    assignedTo: 'Elena Rostova',
    sourceNoteId: 'keep-2',
    sourceNoteTitle: 'NDIS Commission Monthly Submission Checklist',
    clientId: 'cli-103',
    clientName: 'Liam O’Connor',
    isSyncedFromKeep: true,
    createdAt: '2026-08-14T11:00:00Z',
    updatedAt: '2026-08-15T08:00:00Z'
  },
  {
    id: 'task-103',
    title: 'Draft Service Agreement schedule for FBA & Interim Plan',
    description: 'Follow up with Jessica Brooks regarding $42,000 NDIS funding allocation.',
    category: 'Financial',
    priority: 'High',
    status: 'In Progress',
    dueDate: '2026-08-24',
    assignedTo: 'Dr. Sarah Jenkins',
    leadId: 'lead-601',
    leadName: 'Ethan Brooks',
    isSyncedFromKeep: false,
    createdAt: '2026-08-14T11:00:00Z',
    updatedAt: '2026-08-14T11:00:00Z'
  },
  {
    id: 'task-104',
    title: 'Sign off on interim BSP v2.1 with Principal Specialist',
    description: 'Present ABC scatterplot analysis and schedule parent feedback videoconference.',
    category: 'Clinical',
    priority: 'Medium',
    status: 'Pending',
    dueDate: '2026-08-28',
    assignedTo: 'Marcus Vance',
    sourceNoteId: 'keep-3',
    sourceNoteTitle: 'Supervision Session Agenda with Principal Specialist',
    isSyncedFromKeep: true,
    createdAt: '2026-08-13T14:20:00Z',
    updatedAt: '2026-08-14T16:00:00Z'
  },
  {
    id: 'task-105',
    title: 'Verify worker screening renewals for PBS supervision roster',
    description: 'Ensure provisional practitioner WWCC and NDIS orientation completion checks are logged.',
    category: 'HR',
    priority: 'Medium',
    status: 'Pending',
    dueDate: '2026-08-30',
    assignedTo: 'Elena Rostova',
    isSyncedFromKeep: false,
    createdAt: '2026-08-12T10:00:00Z',
    updatedAt: '2026-08-12T10:00:00Z'
  }
];

export const INITIAL_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'log-1001',
    timestamp: '2026-08-15T09:30:00Z',
    actorId: 'user-director',
    actorName: 'Dr. Sarah Jenkins',
    actorRole: 'ADMIN',
    action: 'LOGIN',
    entity: 'SystemSession',
    entityId: 'sess-8819',
    details: 'Authenticated via Google Workspace SSO into Breakthrough OS',
    ipAddress: '10.0.0.1'
  },
  {
    id: 'log-1002',
    timestamp: '2026-08-14T16:00:00Z',
    actorId: 'user-specialist',
    actorName: 'Marcus Vance',
    actorRole: 'PRACTITIONER',
    action: 'CREATE',
    entity: 'CaseNote',
    entityId: 'note-501',
    details: 'Logged SOAP clinical session note for Jordan Miller with auto-billing claim',
    ipAddress: '10.0.0.1'
  }
];
